server:
    port: 9000

spring:
    application:
        name: logging
management:
    endpoints:
        web:
            exposure:
                include: loggers
#logging:
#    level:
#        root: WARN
#        com:
#            github:
#                edgar615: INFO
#    file: logging.log
#    path: log # 日志文件为 spring.log,和logging.file不能同时使用，如若同时使用，则只有logging.file生效
#    pattern:
#        console: "%date %level %msg%n"
#    config: "classpath:logback-spring.xml"

#logging:
#    config: # Location of the logging configuration file. For instance, `classpath:logback.xml`for Logback.
#    exception-conversion-word: %wEx # Conversion word used when logging exceptions.
#    file: # Log file name (for instance, `myapp.log`). Names can be an exact location or relative to the current directory.
#        max-history: 0 # Maximum of archive log files to keep. Only supported with the default logback setup.
#        max-size: 10MB # Maximum log file size. Only supported with the default logback setup.
#    level.*: # Log levels severity mapping. For instance, `logging.level.org.springframework=DEBUG`.
#    path= # Location of the log file. For instance, `/var/log`.
#    pattern:
#        console: # Appender pattern for output to the console. Supported only with the default Logback setup.
#        dateformat: yyyy-MM-dd HH:mm:ss.SSS # Appender pattern for log date format. Supported only with the default Logback setup.
#        file: # Appender pattern for output to a file. Supported only with the default Logback setup.
#        level: %5p # Appender pattern for log level. Supported only with the default Logback setup.
#    register-shutdown-hook: false # Register a shutdown hook for the logging system when it is initialized.
