server:
    port: 9000

spring:
    application:
        name: consul-sample
    cloud:
        consul:
        host: localhost
        port: 8500
        discovery:
            tags: foo=bar, baz
            healthCheckPath: ${management.context-path}/health
            healthCheckInterval: 15s
            instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}