server:
    port: 9001

spring:
    application:
        name: gateway-service

info:
    name: @project.artifactId@
    build:
        artifact:   @project.artifactId@
        name: @project.artifactId@
        version: @project.version@
        description: 这是一个测试用例
