server:
  port: 9000
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
       - id: service1
         uri: http://localhost:9001/v1
         predicates:
         - Path=/hello
         - Weight=service1, 95
       - id: service2
         uri: http://localhost:9001/v2
         predicates:
         - Path=/hello
         - Weight=service2, 5