server:
    port: 9000

spring:
#    cloud:
#        consul:
#            host: localhost
#            port: 8500
    application:
        name: @project.artifactId@
    boot:
        admin:
            client:
                url: "http://localhost:8088"
#                username: user
#                password: password
#                instance:
#                    metadata:
#                        user.name: user
#                        user.password: password
info:
    name: @project.artifactId@
    build:
        artifact:   @project.artifactId@
        name: @project.artifactId@
        version: @project.version@
        description: 这是一个测试用例

management:
    info:
        defaults:
            enabled: true
    endpoint:
          health:
            show-details: "ALWAYS"
          beans:
                enabled: true
          prometheus:
                enabled: true
          shutdown:
                enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /manage