server:
    port: 9001

spring:
    application:
        name: feign-sample
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckPath: /health
                healthCheckInterval: 15s

feign:
      hystrix:
          enabled: true

management:
    endpoints:
        web:
            base-path: /manage