server:
    port: 8088

spring:
#    cloud:
#        consul:
#            host: localhost
#            port: 8500
    application:
        name: admin
    jackson:
        serialization-inclusion: non_null
    mail:
        host: smtp.xxxxx.com
        username: xxxxx@xxxx.com
        password: xxxxxxx
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        requied: true
#    security: #配了这个后client注册失败，一直没找到原因，猜测的client没有写入响应请求头
#        user:
#            name: user
#            password: password
    boot:
        admin:
            notify:
                mail:
                    enabled: true
                    ignore-changes: "UNKNOWN:UP"
#                    ignore-changes: "*:UP"
#                    ignore-changes:
#                        - "UNKNOWN:UP"
#                        - "OFFLINE:UP"
                    to: xxx@xxx.com
                    from: xxxx@xxxx.com
