server:
    port: 9002

spring:
    application:
        name: zipkin-client2
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckPath: /manage/health
                healthCheckInterval: 15s
    zipkin:
        base-url: http://localhost:9000
    sleuth:
        sampler:
            percentage: 1.0 #是监控的百分比，默认的是0.1表示10%,这里给1.0表示全部监控

info:
    name: @project.artifactId@
    build:
        artifact:   @project.artifactId@
        name: @project.artifactId@
        version: @project.version@
        description: 这是一个测试用例

feign:
      hystrix:
          enabled: false

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000

management:
    info:
        defaults:
            enabled: true
    endpoint:
          health:
            show-details: "ALWAYS"
          beans:
                enabled: true
          prometheus:
                enabled: true
          shutdown:
                enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /manage